services:
  mysql:
    image: "mysql:8.0"
    env_file:
      - ./envs/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html

  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - 8081:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  vite:
    image: node:20
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173" # <-- expose Vite's dev server port
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true #makes the frontend run in "interective mode"
    tty: true #makes the frontend run in "interective mode"

  # UTILITY CONTAINERS

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html # we expose our souce code directory to this image througn binding
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    image: node:20
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"] # <-- This line ensures it runs `npm` instead of Linux `install`

  npm-frontend:
    build:
      context: ./dockerfiles
      dockerfile: frontend.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app

volumes:
  mysql_data:
